"use client";

// ── Supported languages ───────────────────────────────────────────────────────
export const LANGUAGES = {
  en: "English",
  pl: "Polski",
  cy: "Cymraeg",
  ro: "Română",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  pt: "Português",
  it: "Italiano",
  lt: "Lietuvių",
  lv: "Latviešu",
  uk: "Українська",
} as const;

export type LangCode = keyof typeof LANGUAGES;

// ── Translation keys ──────────────────────────────────────────────────────────
export type Translations = {
  // Navigation
  nav: { home: string; quotes: string; stats: string };
  // Quote statuses
  status: { draft: string; sent: string; accepted: string; declined: string };
  // Common actions
  common: {
    save: string; saving: string; saved: string; cancel: string; edit: string;
    delete: string; send: string; view: string; back: string; loading: string;
    confirm: string; close: string; add: string; remove: string; copy: string;
    copied: string; upgrade: string; tryAgain: string; signOut: string;
    settings: string; done: string;
  };
  // Home page
  home: {
    title: string; newQuote: string; recent: string; chaseUp: string;
    newRequests: string; revenueThisMonth: string; acceptanceRate: string;
    outstandingQuotes: string; depositsWaiting: string; noQuotes: string;
    sentAgo: string; noReply: string; chaseViaWhatsapp: string;
    getStarted: string; step1: string; step1sub: string; step2: string;
    step2sub: string; step3: string; step3sub: string;
    limitReached: string; lastQuote: string; quoteThemButton: string;
  };
  // Quote flow
  quote: {
    newTitle: string; reviewTitle: string; sendTitle: string;
    customer: string; address: string; email: string; notes: string;
    materials: string; labour: string; total: string; deposit: string;
    validFor: string; days: string; addItem: string; deleteItem: string;
    priceUpdated: string; generate: string; generating: string;
    recording: string; stopRecording: string; startRecording: string;
    orTypeBelow: string; describeJob: string; sendViaWhatsapp: string;
    sendViaEmail: string; copyLink: string; downloadPdf: string;
    duplicate: string; markDeclined: string; invoice: string;
    expiresOn: string; expired: string; subtotal: string;
    vatAmount: string; totalIncVat: string; noBankDetails: string;
    noBankDetailsSub: string;
  };
  // Analytics
  analytics: {
    title: string; totalQuoted: string; accepted: string; totalRevenue: string;
    averageQuote: string; depositsWaiting: string; byStatus: string;
    taxEstimate: string; taxSub: string; expenses: string; grossRevenue: string;
    lessExpenses: string; taxableProfit: string; incomeTax: string;
    classNI: string; totalTax: string; effectiveRate: string;
    paymentsOnAccount: string; setAside: string; perMonth: string;
    disclaimer: string;
  };
  // History
  history: { title: string; search: string; noResults: string };
  // Settings
  settings: {
    title: string; business: string; bankDetails: string; quoteDefaults: string;
    notifications: string; appearance: string; language: string; billing: string;
    account: string; businessName: string; trade: string; phone: string;
    bankName: string; sortCode: string; accountNumber: string; paymentLink: string;
    googleReviewLink: string; validDays: string; depositDefault: string;
    depositPercent: string; vatRegistered: string; vatNumber: string;
    quotePrefix: string; startingNumber: string; paymentTerms: string;
    exclusions: string; notifyAccepted: string; theme: string;
    light: string; dark: string; system: string; saveChanges: string;
    completeSetup: string; completeSetupSub: string; currentPlan: string;
    manageBilling: string; upgradePlan: string;
    quoteNumbering: string; quoteTemplate: string; priceBook: string;
    shareLink: string; data: string; about: string;
    emailAddress: string; newPassword: string; updatePassword: string;
    branding: string;
  };
  // Customer portal
  portal: {
    from: string; jobTitle: string; quoteRef: string; validUntil: string;
    expired: string; acceptQuote: string; declineQuote: string;
    askQuestion: string; accepted: string; acceptedSub: string;
    declined: string; declinedSub: string; signHere: string;
    clearSignature: string; confirmAccept: string; depositDue: string;
    finalPaymentDue: string; payDeposit: string; payFinal: string;
  };
};

// ── All translations ──────────────────────────────────────────────────────────
export const t: Record<LangCode, Translations> = {
  en: {
    nav: { home: "HOME", quotes: "QUOTES", stats: "STATS" },
    status: { draft: "Draft", sent: "Sent", accepted: "Accepted", declined: "Declined" },
    common: { save: "Save", saving: "Saving…", saved: "Saved", cancel: "Cancel", edit: "Edit", delete: "Delete", send: "Send", view: "View", back: "Back", loading: "Loading…", confirm: "Confirm", close: "Close", add: "Add", remove: "Remove", copy: "Copy", copied: "Copied!", upgrade: "Upgrade", tryAgain: "Try again", signOut: "Sign out", settings: "Settings", done: "Done" },
    home: { title: "Dashboard", newQuote: "New Quote", recent: "Recent", chaseUp: "Chase Up", newRequests: "New Requests", revenueThisMonth: "Revenue this month", acceptanceRate: "Acceptance rate", outstandingQuotes: "Outstanding quotes", depositsWaiting: "Deposits waiting", noQuotes: "Nothing here yet — tap New Quote above to create your first one.", sentAgo: "{n}d ago · no reply", noReply: "no reply", chaseViaWhatsapp: "Chase via WhatsApp", getStarted: "Get started in 3 steps", step1: "Add your business name", step1sub: "Settings → Business", step2: "Record your first job", step2sub: "Tap New Quote and describe the work", step3: "Send it to your customer", step3sub: "Via WhatsApp or email in seconds", limitReached: "Monthly limit reached — upgrade to send more", lastQuote: "Last free quote this month", quoteThemButton: "Quote them" },
    quote: { newTitle: "New Quote", reviewTitle: "Review Quote", sendTitle: "Send Quote", customer: "Customer", address: "Address", email: "Email", notes: "Notes", materials: "Materials", labour: "Labour", total: "Total", deposit: "Deposit", validFor: "Valid for", days: "days", addItem: "Add item", deleteItem: "Delete", priceUpdated: "Price updated", generate: "Generate Quote", generating: "Generating…", recording: "Recording…", stopRecording: "Stop", startRecording: "Hold to record", orTypeBelow: "Or type below", describeJob: "Describe the job…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Copy link", downloadPdf: "PDF", duplicate: "Dup.", markDeclined: "Mark as declined", invoice: "Invoice", expiresOn: "Expires", expired: "Expired", subtotal: "Subtotal (ex. VAT)", vatAmount: "VAT (20%)", totalIncVat: "Total inc. VAT", noBankDetails: "Bank details not added", noBankDetailsSub: "Add them in Settings so customers know how to pay." },
    analytics: { title: "Analytics", totalQuoted: "Total quoted", accepted: "Accepted", totalRevenue: "Total revenue", averageQuote: "Average quote", depositsWaiting: "Deposits waiting", byStatus: "By status", taxEstimate: "HMRC Tax Estimate", taxSub: "Based on accepted revenue", expenses: "Business expenses (£)", grossRevenue: "Gross revenue", lessExpenses: "Less expenses", taxableProfit: "Taxable profit", incomeTax: "Income tax (est.)", classNI: "Class 4 NI (est.)", totalTax: "Total tax due", effectiveRate: "Effective tax rate", paymentsOnAccount: "Payments on account", setAside: "Set aside", perMonth: "per month", disclaimer: "This is an estimate only. Always consult a qualified accountant." },
    history: { title: "All Quotes", search: "Search quotes…", noResults: "No quotes match your search." },
    settings: { title: "Settings", business: "Business", bankDetails: "Bank Details", quoteDefaults: "Quote Defaults", notifications: "Notifications", appearance: "Appearance", language: "Language", billing: "Billing", account: "Account", businessName: "Business name", trade: "Trade", phone: "Phone", bankName: "Bank name", sortCode: "Sort code", accountNumber: "Account number", paymentLink: "Payment link", googleReviewLink: "Google review link", validDays: "Default valid days", depositDefault: "Deposit by default", depositPercent: "Deposit %", vatRegistered: "VAT registered", vatNumber: "VAT number", quotePrefix: "Quote prefix", startingNumber: "Starting number", paymentTerms: "Payment terms", exclusions: "Standard exclusions", notifyAccepted: "Notify when accepted", theme: "Theme", light: "Light", dark: "Dark", system: "System", saveChanges: "Save Changes", completeSetup: "Set up your business profile", completeSetupSub: "Add your business name and bank details so customers know who to pay.", currentPlan: "Current plan", manageBilling: "Manage billing", upgradePlan: "Upgrade plan", quoteNumbering: "Quote numbering", quoteTemplate: "Quote template", priceBook: "Price book", shareLink: "Quote request link", data: "Data", about: "About", emailAddress: "Email address", newPassword: "New password", updatePassword: "Update password", branding: "Branding" },
    portal: { from: "Quote from", jobTitle: "Job", quoteRef: "Quote ref", validUntil: "Valid until", expired: "This quote has expired", acceptQuote: "Accept Quote", declineQuote: "Decline", askQuestion: "Ask a question", accepted: "Quote Accepted", acceptedSub: "Thanks! We'll be in touch to confirm next steps.", declined: "Quote Declined", declinedSub: "Thanks for letting us know.", signHere: "Sign here", clearSignature: "Clear", confirmAccept: "Confirm & Accept", depositDue: "Deposit due", finalPaymentDue: "Final payment due", payDeposit: "Pay deposit", payFinal: "Pay final balance" },
  },

  pl: {
    nav: { home: "STRONA", quotes: "WYCENY", stats: "STATYSTYKI" },
    status: { draft: "Szkic", sent: "Wysłano", accepted: "Zaakceptowano", declined: "Odrzucono" },
    common: { save: "Zapisz", saving: "Zapisywanie…", saved: "Zapisano", cancel: "Anuluj", edit: "Edytuj", delete: "Usuń", send: "Wyślij", view: "Podgląd", back: "Wróć", loading: "Ładowanie…", confirm: "Potwierdź", close: "Zamknij", add: "Dodaj", remove: "Usuń", copy: "Kopiuj", copied: "Skopiowano!", upgrade: "Ulepsz", tryAgain: "Spróbuj ponownie", signOut: "Wyloguj", settings: "Ustawienia", done: "Gotowe" },
    home: { title: "Pulpit", newQuote: "Nowa Wycena", recent: "Ostatnie", chaseUp: "Przypomnienia", newRequests: "Nowe Zapytania", revenueThisMonth: "Przychód w tym miesiącu", acceptanceRate: "Wskaźnik akceptacji", outstandingQuotes: "Oczekujące wyceny", depositsWaiting: "Zaliczki do opłacenia", noQuotes: "Brak wycen — dotknij Nowa Wycena, aby utworzyć pierwszą.", sentAgo: "{n}d temu · brak odpowiedzi", noReply: "brak odpowiedzi", chaseViaWhatsapp: "Przypomnij przez WhatsApp", getStarted: "Zacznij w 3 krokach", step1: "Dodaj nazwę firmy", step1sub: "Ustawienia → Firma", step2: "Nagraj swoje pierwsze zlecenie", step2sub: "Dotknij Nowa Wycena i opisz pracę", step3: "Wyślij do klienta", step3sub: "Przez WhatsApp lub email w kilka sekund", limitReached: "Osiągnięto miesięczny limit — ulepsz plan", lastQuote: "Ostatnia darmowa wycena w tym miesiącu", quoteThemButton: "Wyceń" },
    quote: { newTitle: "Nowa Wycena", reviewTitle: "Przegląd Wyceny", sendTitle: "Wyślij Wycenę", customer: "Klient", address: "Adres", email: "Email", notes: "Notatki", materials: "Materiały", labour: "Robocizna", total: "Łącznie", deposit: "Zaliczka", validFor: "Ważna przez", days: "dni", addItem: "Dodaj pozycję", deleteItem: "Usuń", priceUpdated: "Cena zaktualizowana", generate: "Generuj Wycenę", generating: "Generowanie…", recording: "Nagrywanie…", stopRecording: "Zatrzymaj", startRecording: "Przytrzymaj, aby nagrać", orTypeBelow: "Lub wpisz poniżej", describeJob: "Opisz zlecenie…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Kopiuj link", downloadPdf: "PDF", duplicate: "Duplikuj", markDeclined: "Oznacz jako odrzucone", invoice: "Faktura", expiresOn: "Wygasa", expired: "Wygasło", subtotal: "Suma netto", vatAmount: "VAT (20%)", totalIncVat: "Suma z VAT", noBankDetails: "Brak danych bankowych", noBankDetailsSub: "Dodaj je w Ustawieniach, aby klienci wiedzieli jak zapłacić." },
    analytics: { title: "Statystyki", totalQuoted: "Łączna wartość wycen", accepted: "Zaakceptowane", totalRevenue: "Łączny przychód", averageQuote: "Średnia wycena", depositsWaiting: "Zaliczki do opłacenia", byStatus: "Według statusu", taxEstimate: "Szacunek podatku HMRC", taxSub: "Na podstawie zaakceptowanych przychodów", expenses: "Koszty firmowe (£)", grossRevenue: "Przychód brutto", lessExpenses: "Minus koszty", taxableProfit: "Dochód do opodatkowania", incomeTax: "Podatek dochodowy (szac.)", classNI: "NI Klasa 4 (szac.)", totalTax: "Łączny podatek", effectiveRate: "Efektywna stopa podatkowa", paymentsOnAccount: "Zaliczki na podatek", setAside: "Odłóż", perMonth: "miesięcznie", disclaimer: "To jest tylko szacunek. Skonsultuj się z księgowym." },
    history: { title: "Wszystkie Wyceny", search: "Szukaj wycen…", noResults: "Brak wyników." },
    settings: { title: "Ustawienia", business: "Firma", bankDetails: "Dane Bankowe", quoteDefaults: "Domyślne Wyceny", notifications: "Powiadomienia", appearance: "Wygląd", language: "Język", billing: "Rozliczenia", account: "Konto", businessName: "Nazwa firmy", trade: "Branża", phone: "Telefon", bankName: "Nazwa banku", sortCode: "Kod sortowania", accountNumber: "Numer konta", paymentLink: "Link do płatności", googleReviewLink: "Link do opinii Google", validDays: "Domyślna ważność (dni)", depositDefault: "Zaliczka domyślnie", depositPercent: "Procent zaliczki", vatRegistered: "Płatnik VAT", vatNumber: "Numer VAT", quotePrefix: "Prefiks wyceny", startingNumber: "Numer startowy", paymentTerms: "Warunki płatności", exclusions: "Standardowe wykluczenia", notifyAccepted: "Powiadamiaj o akceptacji", theme: "Motyw", light: "Jasny", dark: "Ciemny", system: "Systemowy", saveChanges: "Zapisz Zmiany", completeSetup: "Uzupełnij profil firmy", completeSetupSub: "Dodaj nazwę firmy i dane bankowe.", currentPlan: "Aktualny plan", manageBilling: "Zarządzaj rozliczeniami", upgradePlan: "Ulepsz plan", quoteNumbering: "Numeracja wycen", quoteTemplate: "Szablon wyceny", priceBook: "Cennik", shareLink: "Link do wyceny", data: "Dane", about: "O aplikacji", emailAddress: "Adres e-mail", newPassword: "Nowe hasło", updatePassword: "Zmień hasło", branding: "Branding" },
    portal: { from: "Wycena od", jobTitle: "Zlecenie", quoteRef: "Nr wyceny", validUntil: "Ważna do", expired: "Ta wycena wygasła", acceptQuote: "Zaakceptuj Wycenę", declineQuote: "Odrzuć", askQuestion: "Zadaj pytanie", accepted: "Wycena Zaakceptowana", acceptedSub: "Dziękujemy! Skontaktujemy się wkrótce.", declined: "Wycena Odrzucona", declinedSub: "Dziękujemy za informację.", signHere: "Podpisz tutaj", clearSignature: "Wyczyść", confirmAccept: "Potwierdź i Zaakceptuj", depositDue: "Zaliczka do zapłaty", finalPaymentDue: "Płatność końcowa", payDeposit: "Zapłać zaliczkę", payFinal: "Zapłać saldo" },
  },

  cy: {
    nav: { home: "HAFAN", quotes: "DYFYNBRISIAU", stats: "YSTADEGAU" },
    status: { draft: "Drafft", sent: "Anfonwyd", accepted: "Derbyniwyd", declined: "Gwrthodwyd" },
    common: { save: "Cadw", saving: "Cadw…", saved: "Wedi cadw", cancel: "Canslo", edit: "Golygu", delete: "Dileu", send: "Anfon", view: "Gweld", back: "Yn ôl", loading: "Llwytho…", confirm: "Cadarnhau", close: "Cau", add: "Ychwanegu", remove: "Tynnu", copy: "Copïo", copied: "Wedi copïo!", upgrade: "Uwchraddio", tryAgain: "Ceisio eto", signOut: "Allgofnodi", settings: "Gosodiadau", done: "Gorffenwyd" },
    home: { title: "Dangosfwrdd", newQuote: "Dyfynbris Newydd", recent: "Diweddar", chaseUp: "Dilyn I Fyny", newRequests: "Ceisiadau Newydd", revenueThisMonth: "Refeniw y mis hwn", acceptanceRate: "Cyfradd dderbyn", outstandingQuotes: "Dyfynbrisiau am sylw", depositsWaiting: "Blaendaliadau'n aros", noQuotes: "Dim byd eto — tapiwch Dyfynbris Newydd.", sentAgo: "{n}d yn ôl · dim ateb", noReply: "dim ateb", chaseViaWhatsapp: "Dilyn trwy WhatsApp", getStarted: "Cychwyn mewn 3 cam", step1: "Ychwanegu enw'r busnes", step1sub: "Gosodiadau → Busnes", step2: "Recordio'ch swydd gyntaf", step2sub: "Tapiwch Dyfynbris Newydd", step3: "Ei anfon at eich cwsmer", step3sub: "Trwy WhatsApp neu e-bost", limitReached: "Cyrhaeddwyd y terfyn misol", lastQuote: "Dyfynbris rhad ac am ddim olaf", quoteThemButton: "Dyfynnu" },
    quote: { newTitle: "Dyfynbris Newydd", reviewTitle: "Adolygu", sendTitle: "Anfon", customer: "Cwsmer", address: "Cyfeiriad", email: "E-bost", notes: "Nodiadau", materials: "Deunyddiau", labour: "Llafur", total: "Cyfanswm", deposit: "Blaendal", validFor: "Dilys am", days: "diwrnod", addItem: "Ychwanegu eitem", deleteItem: "Dileu", priceUpdated: "Pris wedi'i ddiweddaru", generate: "Cynhyrchu Dyfynbris", generating: "Cynhyrchu…", recording: "Recordio…", stopRecording: "Stopio", startRecording: "Dal i recordio", orTypeBelow: "Neu deipiwch isod", describeJob: "Disgrifio'r gwaith…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "E-bost", copyLink: "Copïo dolen", downloadPdf: "PDF", duplicate: "Dyblygu", markDeclined: "Nodi fel gwrthodwyd", invoice: "Anfoneb", expiresOn: "Daw i ben", expired: "Wedi dod i ben", subtotal: "Is-gyfanswm (heb TAW)", vatAmount: "TAW (20%)", totalIncVat: "Cyfanswm gyda TAW", noBankDetails: "Dim manylion banc", noBankDetailsSub: "Ychwanegwch yn y Gosodiadau." },
    analytics: { title: "Dadansoddeg", totalQuoted: "Cyfanswm dyfynbrisiau", accepted: "Derbyniwyd", totalRevenue: "Cyfanswm refeniw", averageQuote: "Dyfynbris cyfartalog", depositsWaiting: "Blaendaliadau'n aros", byStatus: "Yn ôl statws", taxEstimate: "Amcangyfrif Treth HMRC", taxSub: "Yn seiliedig ar refeniw derbyniwyd", expenses: "Costau busnes (£)", grossRevenue: "Refeniw gros", lessExpenses: "Llai costau", taxableProfit: "Elw trethadwy", incomeTax: "Treth incwm (amcan.)", classNI: "YG Dosbarth 4 (amcan.)", totalTax: "Cyfanswm treth", effectiveRate: "Cyfradd dreth effeithiol", paymentsOnAccount: "Taliadau ar gyfrif", setAside: "Neilltuo", perMonth: "y mis", disclaimer: "Amcangyfrif yn unig. Ymgynghorwch â chyfrifydd." },
    history: { title: "Pob Dyfynbris", search: "Chwilio…", noResults: "Dim canlyniadau." },
    settings: { title: "Gosodiadau", business: "Busnes", bankDetails: "Manylion Banc", quoteDefaults: "Rhagosodiadau", notifications: "Hysbysiadau", appearance: "Ymddangosiad", language: "Iaith", billing: "Bilio", account: "Cyfrif", businessName: "Enw'r busnes", trade: "Masnach", phone: "Ffôn", bankName: "Enw'r banc", sortCode: "Cod didoli", accountNumber: "Rhif cyfrif", paymentLink: "Dolen talu", googleReviewLink: "Dolen adolygiad Google", validDays: "Dyddiau dilysrwydd", depositDefault: "Blaendal yn ddiofyn", depositPercent: "% blaendal", vatRegistered: "Cofrestredig TAW", vatNumber: "Rhif TAW", quotePrefix: "Rhagddodiad", startingNumber: "Rhif cychwyn", paymentTerms: "Telerau talu", exclusions: "Eithriadau safonol", notifyAccepted: "Hysbysu pan dderbyniwyd", theme: "Thema", light: "Golau", dark: "Tywyll", system: "System", saveChanges: "Cadw Newidiadau", completeSetup: "Cwblhewch eich proffil", completeSetupSub: "Ychwanegwch enw'r busnes a manylion banc.", currentPlan: "Cynllun presennol", manageBilling: "Rheoli bilio", upgradePlan: "Uwchraddio cynllun", quoteNumbering: "Rhifo dyfynbrisiau", quoteTemplate: "Templed dyfynbris", priceBook: "Llyfr prisiau", shareLink: "Dolen cais dyfynbris", data: "Data", about: "Ynghylch", emailAddress: "Cyfeiriad e-bost", newPassword: "Cyfrinair newydd", updatePassword: "Diweddaru cyfrinair", branding: "Brandio" },
    portal: { from: "Dyfynbris gan", jobTitle: "Swydd", quoteRef: "Cyfeirnod", validUntil: "Dilys tan", expired: "Mae'r dyfynbris hwn wedi dod i ben", acceptQuote: "Derbyn Dyfynbris", declineQuote: "Gwrthod", askQuestion: "Gofyn cwestiwn", accepted: "Dyfynbris Wedi'i Dderbyn", acceptedSub: "Diolch! Byddwn mewn cysylltiad.", declined: "Dyfynbris Wedi'i Wrthod", declinedSub: "Diolch am roi gwybod.", signHere: "Arwyddwch yma", clearSignature: "Clirio", confirmAccept: "Cadarnhau a Derbyn", depositDue: "Blaendal i'w dalu", finalPaymentDue: "Taliad terfynol i'w dalu", payDeposit: "Talu blaendal", payFinal: "Talu balans" },
  },

  ro: {
    nav: { home: "ACASĂ", quotes: "OFERTE", stats: "STATISTICI" },
    status: { draft: "Schiță", sent: "Trimis", accepted: "Acceptat", declined: "Refuzat" },
    common: { save: "Salvează", saving: "Se salvează…", saved: "Salvat", cancel: "Anulează", edit: "Editează", delete: "Șterge", send: "Trimite", view: "Vezi", back: "Înapoi", loading: "Se încarcă…", confirm: "Confirmă", close: "Închide", add: "Adaugă", remove: "Elimină", copy: "Copiază", copied: "Copiat!", upgrade: "Îmbunătățește", tryAgain: "Încearcă din nou", signOut: "Deconectare", settings: "Setări", done: "Gata" },
    home: { title: "Tablou de bord", newQuote: "Ofertă Nouă", recent: "Recente", chaseUp: "Urmărire", newRequests: "Cereri Noi", revenueThisMonth: "Venituri luna aceasta", acceptanceRate: "Rata de acceptare", outstandingQuotes: "Oferte în așteptare", depositsWaiting: "Avansuri în așteptare", noQuotes: "Nimic deocamdată — apăsați Ofertă Nouă.", sentAgo: "{n}z în urmă · fără răspuns", noReply: "fără răspuns", chaseViaWhatsapp: "Urmărire WhatsApp", getStarted: "Începe în 3 pași", step1: "Adaugă numele firmei", step1sub: "Setări → Firmă", step2: "Înregistrează prima ta lucrare", step2sub: "Apasă Ofertă Nouă și descrie lucrarea", step3: "Trimite clientului", step3sub: "Prin WhatsApp sau email în câteva secunde", limitReached: "Limita lunară atinsă — îmbunătățește planul", lastQuote: "Ultima ofertă gratuită luna aceasta", quoteThemButton: "Ofertă" },
    quote: { newTitle: "Ofertă Nouă", reviewTitle: "Revizuire Ofertă", sendTitle: "Trimite Oferta", customer: "Client", address: "Adresă", email: "Email", notes: "Note", materials: "Materiale", labour: "Manoperă", total: "Total", deposit: "Avans", validFor: "Valabilă", days: "zile", addItem: "Adaugă articol", deleteItem: "Șterge", priceUpdated: "Preț actualizat", generate: "Generează Ofertă", generating: "Se generează…", recording: "Se înregistrează…", stopRecording: "Stop", startRecording: "Ține apăsat pentru înregistrare", orTypeBelow: "Sau scrie mai jos", describeJob: "Descrie lucrarea…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Copiază link", downloadPdf: "PDF", duplicate: "Duplică", markDeclined: "Marchează ca refuzat", invoice: "Factură", expiresOn: "Expiră", expired: "Expirat", subtotal: "Subtotal (fără TVA)", vatAmount: "TVA (20%)", totalIncVat: "Total cu TVA", noBankDetails: "Date bancare lipsă", noBankDetailsSub: "Adaugă-le în Setări." },
    analytics: { title: "Statistici", totalQuoted: "Total oferte", accepted: "Acceptate", totalRevenue: "Venituri totale", averageQuote: "Ofertă medie", depositsWaiting: "Avansuri în așteptare", byStatus: "După status", taxEstimate: "Estimare taxe HMRC", taxSub: "Bazat pe veniturile acceptate", expenses: "Cheltuieli firmă (£)", grossRevenue: "Venituri brute", lessExpenses: "Minus cheltuieli", taxableProfit: "Profit impozabil", incomeTax: "Impozit pe venit (est.)", classNI: "NI Clasa 4 (est.)", totalTax: "Total taxe", effectiveRate: "Rata efectivă de impozitare", paymentsOnAccount: "Plăți în avans", setAside: "Pune deoparte", perMonth: "pe lună", disclaimer: "Estimare orientativă. Consultați un contabil." },
    history: { title: "Toate Ofertele", search: "Caută oferte…", noResults: "Nicio ofertă găsită." },
    settings: { title: "Setări", business: "Firmă", bankDetails: "Date Bancare", quoteDefaults: "Setări Implicite", notifications: "Notificări", appearance: "Aspect", language: "Limbă", billing: "Facturare", account: "Cont", businessName: "Numele firmei", trade: "Meserie", phone: "Telefon", bankName: "Numele băncii", sortCode: "Cod bancar", accountNumber: "Număr cont", paymentLink: "Link plată", googleReviewLink: "Link recenzie Google", validDays: "Zile de valabilitate", depositDefault: "Avans implicit", depositPercent: "% avans", vatRegistered: "Plătitor TVA", vatNumber: "Număr TVA", quotePrefix: "Prefix ofertă", startingNumber: "Număr de start", paymentTerms: "Termeni de plată", exclusions: "Excluderi standard", notifyAccepted: "Notifică la acceptare", theme: "Temă", light: "Luminoasă", dark: "Întunecată", system: "Sistem", saveChanges: "Salvează Modificările", completeSetup: "Completează profilul firmei", completeSetupSub: "Adaugă numele firmei și datele bancare.", currentPlan: "Plan curent", manageBilling: "Gestionează facturarea", upgradePlan: "Îmbunătățește planul", quoteNumbering: "Numerotare oferte", quoteTemplate: "Șablon ofertă", priceBook: "Listă prețuri", shareLink: "Link cerere ofertă", data: "Date", about: "Despre", emailAddress: "Adresă email", newPassword: "Parolă nouă", updatePassword: "Actualizare parolă", branding: "Branding" },
    portal: { from: "Ofertă de la", jobTitle: "Lucrare", quoteRef: "Ref. ofertă", validUntil: "Valabilă până la", expired: "Această ofertă a expirat", acceptQuote: "Acceptă Oferta", declineQuote: "Refuză", askQuestion: "Pune o întrebare", accepted: "Ofertă Acceptată", acceptedSub: "Mulțumim! Vă vom contacta.", declined: "Ofertă Refuzată", declinedSub: "Vă mulțumim pentru răspuns.", signHere: "Semnați aici", clearSignature: "Șterge", confirmAccept: "Confirmă și Acceptă", depositDue: "Avans de plătit", finalPaymentDue: "Plată finală", payDeposit: "Plătește avans", payFinal: "Plătește soldul" },
  },

  es: {
    nav: { home: "INICIO", quotes: "PRESUPUESTOS", stats: "ESTADÍSTICAS" },
    status: { draft: "Borrador", sent: "Enviado", accepted: "Aceptado", declined: "Rechazado" },
    common: { save: "Guardar", saving: "Guardando…", saved: "Guardado", cancel: "Cancelar", edit: "Editar", delete: "Eliminar", send: "Enviar", view: "Ver", back: "Volver", loading: "Cargando…", confirm: "Confirmar", close: "Cerrar", add: "Añadir", remove: "Quitar", copy: "Copiar", copied: "¡Copiado!", upgrade: "Mejorar", tryAgain: "Intentar de nuevo", signOut: "Cerrar sesión", settings: "Ajustes", done: "Listo" },
    home: { title: "Panel", newQuote: "Nuevo Presupuesto", recent: "Recientes", chaseUp: "Seguimiento", newRequests: "Nuevas Solicitudes", revenueThisMonth: "Ingresos este mes", acceptanceRate: "Tasa de aceptación", outstandingQuotes: "Presupuestos pendientes", depositsWaiting: "Depósitos pendientes", noQuotes: "Nada aún — pulsa Nuevo Presupuesto.", sentAgo: "{n}d atrás · sin respuesta", noReply: "sin respuesta", chaseViaWhatsapp: "Recordar por WhatsApp", getStarted: "Empieza en 3 pasos", step1: "Añade el nombre de tu empresa", step1sub: "Ajustes → Empresa", step2: "Graba tu primer trabajo", step2sub: "Pulsa Nuevo Presupuesto y describe el trabajo", step3: "Envíalo a tu cliente", step3sub: "Por WhatsApp o email en segundos", limitReached: "Límite mensual alcanzado — mejora tu plan", lastQuote: "Último presupuesto gratuito del mes", quoteThemButton: "Presupuestar" },
    quote: { newTitle: "Nuevo Presupuesto", reviewTitle: "Revisar Presupuesto", sendTitle: "Enviar Presupuesto", customer: "Cliente", address: "Dirección", email: "Email", notes: "Notas", materials: "Materiales", labour: "Mano de obra", total: "Total", deposit: "Depósito", validFor: "Válido por", days: "días", addItem: "Añadir elemento", deleteItem: "Eliminar", priceUpdated: "Precio actualizado", generate: "Generar Presupuesto", generating: "Generando…", recording: "Grabando…", stopRecording: "Parar", startRecording: "Mantén pulsado para grabar", orTypeBelow: "O escribe abajo", describeJob: "Describe el trabajo…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Copiar enlace", downloadPdf: "PDF", duplicate: "Duplicar", markDeclined: "Marcar como rechazado", invoice: "Factura", expiresOn: "Expira", expired: "Expirado", subtotal: "Subtotal (sin IVA)", vatAmount: "IVA (20%)", totalIncVat: "Total con IVA", noBankDetails: "Sin datos bancarios", noBankDetailsSub: "Añádelos en Ajustes." },
    analytics: { title: "Estadísticas", totalQuoted: "Total presupuestado", accepted: "Aceptados", totalRevenue: "Ingresos totales", averageQuote: "Presupuesto medio", depositsWaiting: "Depósitos pendientes", byStatus: "Por estado", taxEstimate: "Estimación HMRC", taxSub: "Basado en ingresos aceptados", expenses: "Gastos empresariales (£)", grossRevenue: "Ingresos brutos", lessExpenses: "Menos gastos", taxableProfit: "Beneficio imponible", incomeTax: "IRPF (est.)", classNI: "NI Clase 4 (est.)", totalTax: "Total impuestos", effectiveRate: "Tipo impositivo efectivo", paymentsOnAccount: "Pagos a cuenta", setAside: "Reservar", perMonth: "al mes", disclaimer: "Solo estimación. Consulta un contable." },
    history: { title: "Todos los Presupuestos", search: "Buscar presupuestos…", noResults: "Sin resultados." },
    settings: { title: "Ajustes", business: "Empresa", bankDetails: "Datos Bancarios", quoteDefaults: "Valores por Defecto", notifications: "Notificaciones", appearance: "Apariencia", language: "Idioma", billing: "Facturación", account: "Cuenta", businessName: "Nombre de empresa", trade: "Oficio", phone: "Teléfono", bankName: "Nombre del banco", sortCode: "Código bancario", accountNumber: "Número de cuenta", paymentLink: "Enlace de pago", googleReviewLink: "Enlace de reseña Google", validDays: "Días de validez", depositDefault: "Depósito por defecto", depositPercent: "% depósito", vatRegistered: "Registrado en IVA", vatNumber: "Número IVA", quotePrefix: "Prefijo presupuesto", startingNumber: "Número inicial", paymentTerms: "Condiciones de pago", exclusions: "Exclusiones estándar", notifyAccepted: "Notificar al aceptar", theme: "Tema", light: "Claro", dark: "Oscuro", system: "Sistema", saveChanges: "Guardar Cambios", completeSetup: "Completa tu perfil", completeSetupSub: "Añade nombre de empresa y datos bancarios.", currentPlan: "Plan actual", manageBilling: "Gestionar facturación", upgradePlan: "Mejorar plan", quoteNumbering: "Numeración", quoteTemplate: "Plantilla", priceBook: "Lista de precios", shareLink: "Enlace de solicitud", data: "Datos", about: "Acerca de", emailAddress: "Correo electrónico", newPassword: "Nueva contraseña", updatePassword: "Actualizar contraseña", branding: "Imagen corporativa" },
    portal: { from: "Presupuesto de", jobTitle: "Trabajo", quoteRef: "Ref. presupuesto", validUntil: "Válido hasta", expired: "Este presupuesto ha expirado", acceptQuote: "Aceptar Presupuesto", declineQuote: "Rechazar", askQuestion: "Hacer una pregunta", accepted: "Presupuesto Aceptado", acceptedSub: "¡Gracias! Nos pondremos en contacto.", declined: "Presupuesto Rechazado", declinedSub: "Gracias por avisarnos.", signHere: "Firme aquí", clearSignature: "Borrar", confirmAccept: "Confirmar y Aceptar", depositDue: "Depósito pendiente", finalPaymentDue: "Pago final pendiente", payDeposit: "Pagar depósito", payFinal: "Pagar saldo" },
  },

  fr: {
    nav: { home: "ACCUEIL", quotes: "DEVIS", stats: "STATISTIQUES" },
    status: { draft: "Brouillon", sent: "Envoyé", accepted: "Accepté", declined: "Refusé" },
    common: { save: "Enregistrer", saving: "Enregistrement…", saved: "Enregistré", cancel: "Annuler", edit: "Modifier", delete: "Supprimer", send: "Envoyer", view: "Voir", back: "Retour", loading: "Chargement…", confirm: "Confirmer", close: "Fermer", add: "Ajouter", remove: "Retirer", copy: "Copier", copied: "Copié !", upgrade: "Améliorer", tryAgain: "Réessayer", signOut: "Se déconnecter", settings: "Paramètres", done: "Terminé" },
    home: { title: "Tableau de bord", newQuote: "Nouveau Devis", recent: "Récents", chaseUp: "Relances", newRequests: "Nouvelles Demandes", revenueThisMonth: "Revenus ce mois", acceptanceRate: "Taux d'acceptation", outstandingQuotes: "Devis en attente", depositsWaiting: "Acomptes en attente", noQuotes: "Rien encore — appuyez sur Nouveau Devis.", sentAgo: "{n}j il y a · sans réponse", noReply: "sans réponse", chaseViaWhatsapp: "Relancer par WhatsApp", getStarted: "Commencer en 3 étapes", step1: "Ajouter le nom de votre entreprise", step1sub: "Paramètres → Entreprise", step2: "Enregistrer votre premier chantier", step2sub: "Appuyez sur Nouveau Devis et décrivez le travail", step3: "Envoyer à votre client", step3sub: "Par WhatsApp ou email en quelques secondes", limitReached: "Limite mensuelle atteinte — améliorez votre plan", lastQuote: "Dernier devis gratuit du mois", quoteThemButton: "Devis" },
    quote: { newTitle: "Nouveau Devis", reviewTitle: "Réviser le Devis", sendTitle: "Envoyer le Devis", customer: "Client", address: "Adresse", email: "Email", notes: "Notes", materials: "Matériaux", labour: "Main d'œuvre", total: "Total", deposit: "Acompte", validFor: "Valable", days: "jours", addItem: "Ajouter un article", deleteItem: "Supprimer", priceUpdated: "Prix mis à jour", generate: "Générer un Devis", generating: "Génération…", recording: "Enregistrement…", stopRecording: "Arrêter", startRecording: "Maintenir pour enregistrer", orTypeBelow: "Ou tapez ci-dessous", describeJob: "Décrivez le chantier…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Copier le lien", downloadPdf: "PDF", duplicate: "Dupliquer", markDeclined: "Marquer comme refusé", invoice: "Facture", expiresOn: "Expire le", expired: "Expiré", subtotal: "Sous-total (HT)", vatAmount: "TVA (20%)", totalIncVat: "Total TTC", noBankDetails: "Coordonnées bancaires manquantes", noBankDetailsSub: "Ajoutez-les dans les Paramètres." },
    analytics: { title: "Statistiques", totalQuoted: "Total devisé", accepted: "Acceptés", totalRevenue: "Revenus totaux", averageQuote: "Devis moyen", depositsWaiting: "Acomptes en attente", byStatus: "Par statut", taxEstimate: "Estimation HMRC", taxSub: "Basé sur les revenus acceptés", expenses: "Charges professionnelles (£)", grossRevenue: "Revenus bruts", lessExpenses: "Moins les charges", taxableProfit: "Bénéfice imposable", incomeTax: "Impôt sur le revenu (est.)", classNI: "NI Classe 4 (est.)", totalTax: "Total impôts", effectiveRate: "Taux effectif d'imposition", paymentsOnAccount: "Acomptes provisionnels", setAside: "Mettre de côté", perMonth: "par mois", disclaimer: "Estimation uniquement. Consultez un comptable." },
    history: { title: "Tous les Devis", search: "Rechercher des devis…", noResults: "Aucun résultat." },
    settings: { title: "Paramètres", business: "Entreprise", bankDetails: "Coordonnées Bancaires", quoteDefaults: "Paramètres par Défaut", notifications: "Notifications", appearance: "Apparence", language: "Langue", billing: "Facturation", account: "Compte", businessName: "Nom de l'entreprise", trade: "Métier", phone: "Téléphone", bankName: "Nom de la banque", sortCode: "Code bancaire", accountNumber: "Numéro de compte", paymentLink: "Lien de paiement", googleReviewLink: "Lien avis Google", validDays: "Jours de validité", depositDefault: "Acompte par défaut", depositPercent: "% d'acompte", vatRegistered: "Assujetti TVA", vatNumber: "Numéro TVA", quotePrefix: "Préfixe devis", startingNumber: "Numéro de départ", paymentTerms: "Conditions de paiement", exclusions: "Exclusions standard", notifyAccepted: "Notifier à l'acceptation", theme: "Thème", light: "Clair", dark: "Sombre", system: "Système", saveChanges: "Enregistrer les Modifications", completeSetup: "Complétez votre profil", completeSetupSub: "Ajoutez le nom et les coordonnées bancaires.", currentPlan: "Plan actuel", manageBilling: "Gérer la facturation", upgradePlan: "Améliorer le plan", quoteNumbering: "Numérotation", quoteTemplate: "Modèle de devis", priceBook: "Tarifs", shareLink: "Lien de demande", data: "Données", about: "À propos", emailAddress: "Adresse e-mail", newPassword: "Nouveau mot de passe", updatePassword: "Mettre à jour le mot de passe", branding: "Image de marque" },
    portal: { from: "Devis de", jobTitle: "Chantier", quoteRef: "Réf. devis", validUntil: "Valable jusqu'au", expired: "Ce devis a expiré", acceptQuote: "Accepter le Devis", declineQuote: "Refuser", askQuestion: "Poser une question", accepted: "Devis Accepté", acceptedSub: "Merci ! Nous vous contacterons.", declined: "Devis Refusé", declinedSub: "Merci de nous avoir informés.", signHere: "Signez ici", clearSignature: "Effacer", confirmAccept: "Confirmer et Accepter", depositDue: "Acompte dû", finalPaymentDue: "Paiement final dû", payDeposit: "Payer l'acompte", payFinal: "Payer le solde" },
  },

  de: {
    nav: { home: "START", quotes: "ANGEBOTE", stats: "STATISTIKEN" },
    status: { draft: "Entwurf", sent: "Gesendet", accepted: "Angenommen", declined: "Abgelehnt" },
    common: { save: "Speichern", saving: "Speichern…", saved: "Gespeichert", cancel: "Abbrechen", edit: "Bearbeiten", delete: "Löschen", send: "Senden", view: "Ansehen", back: "Zurück", loading: "Laden…", confirm: "Bestätigen", close: "Schließen", add: "Hinzufügen", remove: "Entfernen", copy: "Kopieren", copied: "Kopiert!", upgrade: "Upgraden", tryAgain: "Erneut versuchen", signOut: "Abmelden", settings: "Einstellungen", done: "Fertig" },
    home: { title: "Dashboard", newQuote: "Neues Angebot", recent: "Zuletzt", chaseUp: "Nachfassen", newRequests: "Neue Anfragen", revenueThisMonth: "Einnahmen diesen Monat", acceptanceRate: "Annahmequote", outstandingQuotes: "Offene Angebote", depositsWaiting: "Ausstehende Anzahlungen", noQuotes: "Noch nichts — tippe auf Neues Angebot.", sentAgo: "{n}T her · keine Antwort", noReply: "keine Antwort", chaseViaWhatsapp: "Per WhatsApp nachfassen", getStarted: "In 3 Schritten starten", step1: "Firmennamen hinzufügen", step1sub: "Einstellungen → Firma", step2: "Ersten Auftrag aufnehmen", step2sub: "Tippe Neues Angebot und beschreibe die Arbeit", step3: "An Kunden senden", step3sub: "Per WhatsApp oder E-Mail in Sekunden", limitReached: "Monatliches Limit erreicht — Upgrade", lastQuote: "Letztes kostenloses Angebot des Monats", quoteThemButton: "Angebot erstellen" },
    quote: { newTitle: "Neues Angebot", reviewTitle: "Angebot prüfen", sendTitle: "Angebot senden", customer: "Kunde", address: "Adresse", email: "E-Mail", notes: "Notizen", materials: "Materialien", labour: "Arbeit", total: "Gesamt", deposit: "Anzahlung", validFor: "Gültig für", days: "Tage", addItem: "Position hinzufügen", deleteItem: "Löschen", priceUpdated: "Preis aktualisiert", generate: "Angebot erstellen", generating: "Erstelle…", recording: "Aufnahme…", stopRecording: "Stopp", startRecording: "Halten zum Aufnehmen", orTypeBelow: "Oder unten eingeben", describeJob: "Auftrag beschreiben…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "E-Mail", copyLink: "Link kopieren", downloadPdf: "PDF", duplicate: "Duplizieren", markDeclined: "Als abgelehnt markieren", invoice: "Rechnung", expiresOn: "Läuft ab", expired: "Abgelaufen", subtotal: "Zwischensumme (netto)", vatAmount: "MwSt. (20%)", totalIncVat: "Gesamt inkl. MwSt.", noBankDetails: "Keine Bankdaten", noBankDetailsSub: "In Einstellungen hinzufügen." },
    analytics: { title: "Statistiken", totalQuoted: "Gesamt angeboten", accepted: "Angenommen", totalRevenue: "Gesamteinnahmen", averageQuote: "Durchschnittangebot", depositsWaiting: "Ausstehende Anzahlungen", byStatus: "Nach Status", taxEstimate: "HMRC Steuerschätzung", taxSub: "Basierend auf angenommenen Einnahmen", expenses: "Betriebsausgaben (£)", grossRevenue: "Bruttoeinnahmen", lessExpenses: "Minus Ausgaben", taxableProfit: "Steuerpflichtiger Gewinn", incomeTax: "Einkommensteuer (Schätz.)", classNI: "NI Klasse 4 (Schätz.)", totalTax: "Gesamtsteuer", effectiveRate: "Effektiver Steuersatz", paymentsOnAccount: "Vorauszahlungen", setAside: "Zurücklegen", perMonth: "pro Monat", disclaimer: "Nur eine Schätzung. Bitte Steuerberater konsultieren." },
    history: { title: "Alle Angebote", search: "Angebote suchen…", noResults: "Keine Ergebnisse." },
    settings: { title: "Einstellungen", business: "Firma", bankDetails: "Bankdaten", quoteDefaults: "Standardwerte", notifications: "Benachrichtigungen", appearance: "Erscheinungsbild", language: "Sprache", billing: "Abrechnung", account: "Konto", businessName: "Firmenname", trade: "Gewerk", phone: "Telefon", bankName: "Bankname", sortCode: "Bankleitzahl", accountNumber: "Kontonummer", paymentLink: "Zahlungslink", googleReviewLink: "Google-Bewertungslink", validDays: "Gültigkeitstage", depositDefault: "Anzahlung standard", depositPercent: "Anzahlung %", vatRegistered: "MwSt.-registriert", vatNumber: "USt-IdNr.", quotePrefix: "Angebotspräfix", startingNumber: "Startnummer", paymentTerms: "Zahlungsbedingungen", exclusions: "Standardausschlüsse", notifyAccepted: "Bei Annahme benachrichtigen", theme: "Design", light: "Hell", dark: "Dunkel", system: "System", saveChanges: "Änderungen speichern", completeSetup: "Profil vervollständigen", completeSetupSub: "Firmenname und Bankdaten hinzufügen.", currentPlan: "Aktueller Plan", manageBilling: "Abrechnung verwalten", upgradePlan: "Plan upgraden", quoteNumbering: "Angebotsnummern", quoteTemplate: "Angebotsvorlage", priceBook: "Preisbuch", shareLink: "Anfrage-Link", data: "Daten", about: "Über", emailAddress: "E-Mail-Adresse", newPassword: "Neues Passwort", updatePassword: "Passwort ändern", branding: "Branding" },
    portal: { from: "Angebot von", jobTitle: "Auftrag", quoteRef: "Angebotsnr.", validUntil: "Gültig bis", expired: "Dieses Angebot ist abgelaufen", acceptQuote: "Angebot annehmen", declineQuote: "Ablehnen", askQuestion: "Frage stellen", accepted: "Angebot Angenommen", acceptedSub: "Danke! Wir melden uns.", declined: "Angebot Abgelehnt", declinedSub: "Danke für die Rückmeldung.", signHere: "Hier unterschreiben", clearSignature: "Löschen", confirmAccept: "Bestätigen und Annehmen", depositDue: "Anzahlung fällig", finalPaymentDue: "Restzahlung fällig", payDeposit: "Anzahlung bezahlen", payFinal: "Restzahlung leisten" },
  },

  pt: {
    nav: { home: "INÍCIO", quotes: "ORÇAMENTOS", stats: "ESTATÍSTICAS" },
    status: { draft: "Rascunho", sent: "Enviado", accepted: "Aceite", declined: "Recusado" },
    common: { save: "Guardar", saving: "A guardar…", saved: "Guardado", cancel: "Cancelar", edit: "Editar", delete: "Eliminar", send: "Enviar", view: "Ver", back: "Voltar", loading: "A carregar…", confirm: "Confirmar", close: "Fechar", add: "Adicionar", remove: "Remover", copy: "Copiar", copied: "Copiado!", upgrade: "Melhorar", tryAgain: "Tentar novamente", signOut: "Sair", settings: "Definições", done: "Concluído" },
    home: { title: "Painel", newQuote: "Novo Orçamento", recent: "Recentes", chaseUp: "Seguimento", newRequests: "Novos Pedidos", revenueThisMonth: "Receita este mês", acceptanceRate: "Taxa de aceitação", outstandingQuotes: "Orçamentos pendentes", depositsWaiting: "Depósitos pendentes", noQuotes: "Nada ainda — toque em Novo Orçamento.", sentAgo: "{n}d atrás · sem resposta", noReply: "sem resposta", chaseViaWhatsapp: "Lembrar via WhatsApp", getStarted: "Começar em 3 passos", step1: "Adicionar nome da empresa", step1sub: "Definições → Empresa", step2: "Gravar o primeiro trabalho", step2sub: "Toque em Novo Orçamento e descreva o trabalho", step3: "Enviar ao cliente", step3sub: "Via WhatsApp ou email em segundos", limitReached: "Limite mensal atingido — melhore o plano", lastQuote: "Último orçamento gratuito do mês", quoteThemButton: "Orçamentar" },
    quote: { newTitle: "Novo Orçamento", reviewTitle: "Rever Orçamento", sendTitle: "Enviar Orçamento", customer: "Cliente", address: "Morada", email: "Email", notes: "Notas", materials: "Materiais", labour: "Mão de obra", total: "Total", deposit: "Depósito", validFor: "Válido por", days: "dias", addItem: "Adicionar item", deleteItem: "Eliminar", priceUpdated: "Preço atualizado", generate: "Gerar Orçamento", generating: "A gerar…", recording: "A gravar…", stopRecording: "Parar", startRecording: "Manter premido para gravar", orTypeBelow: "Ou escreva abaixo", describeJob: "Descreva o trabalho…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Copiar link", downloadPdf: "PDF", duplicate: "Duplicar", markDeclined: "Marcar como recusado", invoice: "Fatura", expiresOn: "Expira", expired: "Expirado", subtotal: "Subtotal (sem IVA)", vatAmount: "IVA (20%)", totalIncVat: "Total com IVA", noBankDetails: "Sem dados bancários", noBankDetailsSub: "Adicione nas Definições." },
    analytics: { title: "Estatísticas", totalQuoted: "Total orçamentado", accepted: "Aceites", totalRevenue: "Receita total", averageQuote: "Orçamento médio", depositsWaiting: "Depósitos pendentes", byStatus: "Por estado", taxEstimate: "Estimativa HMRC", taxSub: "Baseado na receita aceite", expenses: "Despesas da empresa (£)", grossRevenue: "Receita bruta", lessExpenses: "Menos despesas", taxableProfit: "Lucro tributável", incomeTax: "IRS (est.)", classNI: "NI Classe 4 (est.)", totalTax: "Total impostos", effectiveRate: "Taxa efetiva de imposto", paymentsOnAccount: "Pagamentos por conta", setAside: "Reservar", perMonth: "por mês", disclaimer: "Apenas uma estimativa. Consulte um contabilista." },
    history: { title: "Todos os Orçamentos", search: "Pesquisar orçamentos…", noResults: "Sem resultados." },
    settings: { title: "Definições", business: "Empresa", bankDetails: "Dados Bancários", quoteDefaults: "Valores Padrão", notifications: "Notificações", appearance: "Aparência", language: "Idioma", billing: "Faturação", account: "Conta", businessName: "Nome da empresa", trade: "Ofício", phone: "Telefone", bankName: "Nome do banco", sortCode: "Código bancário", accountNumber: "Número de conta", paymentLink: "Link de pagamento", googleReviewLink: "Link de avaliação Google", validDays: "Dias de validade", depositDefault: "Depósito padrão", depositPercent: "% depósito", vatRegistered: "Registado no IVA", vatNumber: "Número IVA", quotePrefix: "Prefixo orçamento", startingNumber: "Número inicial", paymentTerms: "Condições de pagamento", exclusions: "Exclusões padrão", notifyAccepted: "Notificar ao aceitar", theme: "Tema", light: "Claro", dark: "Escuro", system: "Sistema", saveChanges: "Guardar Alterações", completeSetup: "Complete o seu perfil", completeSetupSub: "Adicione nome da empresa e dados bancários.", currentPlan: "Plano atual", manageBilling: "Gerir faturação", upgradePlan: "Melhorar plano", quoteNumbering: "Numeração", quoteTemplate: "Modelo de orçamento", priceBook: "Lista de preços", shareLink: "Link de pedido", data: "Dados", about: "Sobre", emailAddress: "Endereço de email", newPassword: "Nova senha", updatePassword: "Atualizar senha", branding: "Imagem de marca" },
    portal: { from: "Orçamento de", jobTitle: "Trabalho", quoteRef: "Ref. orçamento", validUntil: "Válido até", expired: "Este orçamento expirou", acceptQuote: "Aceitar Orçamento", declineQuote: "Recusar", askQuestion: "Fazer uma pergunta", accepted: "Orçamento Aceite", acceptedSub: "Obrigado! Entraremos em contacto.", declined: "Orçamento Recusado", declinedSub: "Obrigado por nos informar.", signHere: "Assine aqui", clearSignature: "Limpar", confirmAccept: "Confirmar e Aceitar", depositDue: "Depósito devido", finalPaymentDue: "Pagamento final devido", payDeposit: "Pagar depósito", payFinal: "Pagar saldo" },
  },

  it: {
    nav: { home: "HOME", quotes: "PREVENTIVI", stats: "STATISTICHE" },
    status: { draft: "Bozza", sent: "Inviato", accepted: "Accettato", declined: "Rifiutato" },
    common: { save: "Salva", saving: "Salvataggio…", saved: "Salvato", cancel: "Annulla", edit: "Modifica", delete: "Elimina", send: "Invia", view: "Visualizza", back: "Indietro", loading: "Caricamento…", confirm: "Conferma", close: "Chiudi", add: "Aggiungi", remove: "Rimuovi", copy: "Copia", copied: "Copiato!", upgrade: "Aggiorna", tryAgain: "Riprova", signOut: "Esci", settings: "Impostazioni", done: "Fatto" },
    home: { title: "Pannello", newQuote: "Nuovo Preventivo", recent: "Recenti", chaseUp: "Solleciti", newRequests: "Nuove Richieste", revenueThisMonth: "Ricavi questo mese", acceptanceRate: "Tasso di accettazione", outstandingQuotes: "Preventivi in sospeso", depositsWaiting: "Acconti in attesa", noQuotes: "Niente ancora — tocca Nuovo Preventivo.", sentAgo: "{n}g fa · nessuna risposta", noReply: "nessuna risposta", chaseViaWhatsapp: "Sollecita via WhatsApp", getStarted: "Inizia in 3 passi", step1: "Aggiungi il nome dell'azienda", step1sub: "Impostazioni → Azienda", step2: "Registra il primo lavoro", step2sub: "Tocca Nuovo Preventivo e descrivi il lavoro", step3: "Invialo al cliente", step3sub: "Via WhatsApp o email in pochi secondi", limitReached: "Limite mensile raggiunto — aggiorna il piano", lastQuote: "Ultimo preventivo gratuito del mese", quoteThemButton: "Preventiva" },
    quote: { newTitle: "Nuovo Preventivo", reviewTitle: "Revisiona Preventivo", sendTitle: "Invia Preventivo", customer: "Cliente", address: "Indirizzo", email: "Email", notes: "Note", materials: "Materiali", labour: "Manodopera", total: "Totale", deposit: "Acconto", validFor: "Valido per", days: "giorni", addItem: "Aggiungi voce", deleteItem: "Elimina", priceUpdated: "Prezzo aggiornato", generate: "Genera Preventivo", generating: "Generazione…", recording: "Registrazione…", stopRecording: "Stop", startRecording: "Tieni premuto per registrare", orTypeBelow: "O digita qui sotto", describeJob: "Descrivi il lavoro…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Copia link", downloadPdf: "PDF", duplicate: "Duplica", markDeclined: "Segna come rifiutato", invoice: "Fattura", expiresOn: "Scade il", expired: "Scaduto", subtotal: "Subtotale (IVA escl.)", vatAmount: "IVA (20%)", totalIncVat: "Totale IVA incl.", noBankDetails: "Dati bancari mancanti", noBankDetailsSub: "Aggiungili nelle Impostazioni." },
    analytics: { title: "Statistiche", totalQuoted: "Totale preventivato", accepted: "Accettati", totalRevenue: "Ricavi totali", averageQuote: "Preventivo medio", depositsWaiting: "Acconti in attesa", byStatus: "Per stato", taxEstimate: "Stima HMRC", taxSub: "Basato sui ricavi accettati", expenses: "Spese aziendali (£)", grossRevenue: "Ricavi lordi", lessExpenses: "Meno spese", taxableProfit: "Utile imponibile", incomeTax: "IRPEF (st.)", classNI: "NI Classe 4 (st.)", totalTax: "Totale imposte", effectiveRate: "Aliquota effettiva", paymentsOnAccount: "Acconti fiscali", setAside: "Metti da parte", perMonth: "al mese", disclaimer: "Solo una stima. Consulta un commercialista." },
    history: { title: "Tutti i Preventivi", search: "Cerca preventivi…", noResults: "Nessun risultato." },
    settings: { title: "Impostazioni", business: "Azienda", bankDetails: "Dati Bancari", quoteDefaults: "Valori Predefiniti", notifications: "Notifiche", appearance: "Aspetto", language: "Lingua", billing: "Fatturazione", account: "Account", businessName: "Nome azienda", trade: "Mestiere", phone: "Telefono", bankName: "Nome banca", sortCode: "Codice bancario", accountNumber: "Numero conto", paymentLink: "Link pagamento", googleReviewLink: "Link recensione Google", validDays: "Giorni validità", depositDefault: "Acconto predefinito", depositPercent: "% acconto", vatRegistered: "Registrato IVA", vatNumber: "Partita IVA", quotePrefix: "Prefisso preventivo", startingNumber: "Numero iniziale", paymentTerms: "Condizioni di pagamento", exclusions: "Esclusioni standard", notifyAccepted: "Notifica all'accettazione", theme: "Tema", light: "Chiaro", dark: "Scuro", system: "Sistema", saveChanges: "Salva Modifiche", completeSetup: "Completa il profilo", completeSetupSub: "Aggiungi nome azienda e dati bancari.", currentPlan: "Piano attuale", manageBilling: "Gestisci fatturazione", upgradePlan: "Aggiorna piano", quoteNumbering: "Numerazione", quoteTemplate: "Modello preventivo", priceBook: "Listino prezzi", shareLink: "Link richiesta", data: "Dati", about: "Info", emailAddress: "Indirizzo email", newPassword: "Nuova password", updatePassword: "Aggiorna password", branding: "Branding" },
    portal: { from: "Preventivo da", jobTitle: "Lavoro", quoteRef: "Rif. preventivo", validUntil: "Valido fino al", expired: "Questo preventivo è scaduto", acceptQuote: "Accetta Preventivo", declineQuote: "Rifiuta", askQuestion: "Fai una domanda", accepted: "Preventivo Accettato", acceptedSub: "Grazie! Ci metteremo in contatto.", declined: "Preventivo Rifiutato", declinedSub: "Grazie per averci informato.", signHere: "Firma qui", clearSignature: "Cancella", confirmAccept: "Conferma e Accetta", depositDue: "Acconto dovuto", finalPaymentDue: "Saldo dovuto", payDeposit: "Paga acconto", payFinal: "Paga saldo" },
  },

  lt: {
    nav: { home: "PRADŽIA", quotes: "PASIŪLYMAI", stats: "STATISTIKA" },
    status: { draft: "Juodraštis", sent: "Išsiųsta", accepted: "Priimta", declined: "Atmesta" },
    common: { save: "Išsaugoti", saving: "Saugoma…", saved: "Išsaugota", cancel: "Atšaukti", edit: "Redaguoti", delete: "Ištrinti", send: "Siųsti", view: "Peržiūrėti", back: "Atgal", loading: "Kraunama…", confirm: "Patvirtinti", close: "Uždaryti", add: "Pridėti", remove: "Pašalinti", copy: "Kopijuoti", copied: "Nukopijuota!", upgrade: "Atnaujinti", tryAgain: "Bandyti dar kartą", signOut: "Atsijungti", settings: "Nustatymai", done: "Atlikta" },
    home: { title: "Skydelis", newQuote: "Naujas Pasiūlymas", recent: "Naujausi", chaseUp: "Priminimai", newRequests: "Naujos Užklausos", revenueThisMonth: "Pajamos šį mėnesį", acceptanceRate: "Priėmimo rodiklis", outstandingQuotes: "Laukiantys pasiūlymai", depositsWaiting: "Laukiantys avansai", noQuotes: "Dar nieko — bakstelėkite Naujas Pasiūlymas.", sentAgo: "{n}d. prieš · neatsakyta", noReply: "neatsakyta", chaseViaWhatsapp: "Priminti WhatsApp", getStarted: "Pradėkite per 3 žingsnius", step1: "Pridėti įmonės pavadinimą", step1sub: "Nustatymai → Įmonė", step2: "Įrašyti pirmą darbą", step2sub: "Bakstelėkite Naujas Pasiūlymas", step3: "Siųsti klientui", step3sub: "WhatsApp arba el. paštu per kelias sekundes", limitReached: "Pasiekta mėnesio riba — atnaujinkite planą", lastQuote: "Paskutinis nemokamas pasiūlymas", quoteThemButton: "Pasiūlyti" },
    quote: { newTitle: "Naujas Pasiūlymas", reviewTitle: "Peržiūrėti", sendTitle: "Siųsti", customer: "Klientas", address: "Adresas", email: "El. paštas", notes: "Pastabos", materials: "Medžiagos", labour: "Darbas", total: "Iš viso", deposit: "Avansas", validFor: "Galioja", days: "d.", addItem: "Pridėti poziciją", deleteItem: "Ištrinti", priceUpdated: "Kaina atnaujinta", generate: "Generuoti Pasiūlymą", generating: "Generuojama…", recording: "Įrašoma…", stopRecording: "Sustabdyti", startRecording: "Laikykite norėdami įrašyti", orTypeBelow: "Arba rašykite žemiau", describeJob: "Aprašykite darbą…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "El. paštas", copyLink: "Kopijuoti nuorodą", downloadPdf: "PDF", duplicate: "Dublikuoti", markDeclined: "Pažymėti kaip atmestą", invoice: "Sąskaita", expiresOn: "Galioja iki", expired: "Nebegalioja", subtotal: "Tarpinė suma (be PVM)", vatAmount: "PVM (20%)", totalIncVat: "Iš viso su PVM", noBankDetails: "Nėra banko duomenų", noBankDetailsSub: "Pridėkite Nustatymuose." },
    analytics: { title: "Statistika", totalQuoted: "Iš viso pasiūlyta", accepted: "Priimta", totalRevenue: "Visos pajamos", averageQuote: "Vidutinis pasiūlymas", depositsWaiting: "Laukiantys avansai", byStatus: "Pagal statusą", taxEstimate: "HMRC mokesčių įvertis", taxSub: "Remiantis priimtomis pajamomis", expenses: "Verslo išlaidos (£)", grossRevenue: "Bendros pajamos", lessExpenses: "Atėmus išlaidas", taxableProfit: "Apmokestinamas pelnas", incomeTax: "Pajamų mokestis (įvert.)", classNI: "NI 4 klasė (įvert.)", totalTax: "Iš viso mokesčių", effectiveRate: "Efektyvi mokesčio norma", paymentsOnAccount: "Avansiniai mokėjimai", setAside: "Atidėti", perMonth: "per mėnesį", disclaimer: "Tik įvertis. Pasikonsultuokite su buhalteriu." },
    history: { title: "Visi Pasiūlymai", search: "Ieškoti pasiūlymų…", noResults: "Rezultatų nerasta." },
    settings: { title: "Nustatymai", business: "Įmonė", bankDetails: "Banko Duomenys", quoteDefaults: "Numatytieji Nustatymai", notifications: "Pranešimai", appearance: "Išvaizda", language: "Kalba", billing: "Atsiskaitymas", account: "Paskyra", businessName: "Įmonės pavadinimas", trade: "Sritis", phone: "Telefonas", bankName: "Banko pavadinimas", sortCode: "Banko kodas", accountNumber: "Sąskaitos numeris", paymentLink: "Mokėjimo nuoroda", googleReviewLink: "Google atsiliepimų nuoroda", validDays: "Galiojimo dienos", depositDefault: "Avansas pagal nutylėjimą", depositPercent: "Avanso %", vatRegistered: "PVM mokėtojas", vatNumber: "PVM kodas", quotePrefix: "Pasiūlymo prefiksas", startingNumber: "Pradinis numeris", paymentTerms: "Mokėjimo sąlygos", exclusions: "Standartinės išimtys", notifyAccepted: "Pranešti kai priimama", theme: "Tema", light: "Šviesi", dark: "Tamsi", system: "Sistemos", saveChanges: "Išsaugoti Pakeitimus", completeSetup: "Užpildykite profilį", completeSetupSub: "Pridėkite įmonės pavadinimą ir banko duomenis.", currentPlan: "Dabartinis planas", manageBilling: "Tvarkyti atsiskaitymą", upgradePlan: "Atnaujinti planą", quoteNumbering: "Numeravimas", quoteTemplate: "Šablonas", priceBook: "Kainų sąrašas", shareLink: "Užklausos nuoroda", data: "Duomenys", about: "Apie", emailAddress: "El. pašto adresas", newPassword: "Naujas slaptažodis", updatePassword: "Atnaujinti slaptažodį", branding: "Prekės ženklas" },
    portal: { from: "Pasiūlymas iš", jobTitle: "Darbas", quoteRef: "Pasiūlymo nr.", validUntil: "Galioja iki", expired: "Šis pasiūlymas nebegalioja", acceptQuote: "Priimti Pasiūlymą", declineQuote: "Atmesti", askQuestion: "Užduoti klausimą", accepted: "Pasiūlymas Priimtas", acceptedSub: "Ačiū! Susisieksime.", declined: "Pasiūlymas Atmestas", declinedSub: "Ačiū už informaciją.", signHere: "Pasirašykite čia", clearSignature: "Išvalyti", confirmAccept: "Patvirtinti ir Priimti", depositDue: "Mokėtinas avansas", finalPaymentDue: "Galutinis mokėjimas", payDeposit: "Mokėti avansą", payFinal: "Mokėti likutį" },
  },

  lv: {
    nav: { home: "SĀKUMS", quotes: "PIEDĀVĀJUMI", stats: "STATISTIKA" },
    status: { draft: "Melnraksts", sent: "Nosūtīts", accepted: "Pieņemts", declined: "Noraidīts" },
    common: { save: "Saglabāt", saving: "Saglabā…", saved: "Saglabāts", cancel: "Atcelt", edit: "Rediģēt", delete: "Dzēst", send: "Sūtīt", view: "Skatīt", back: "Atpakaļ", loading: "Ielādē…", confirm: "Apstiprināt", close: "Aizvērt", add: "Pievienot", remove: "Noņemt", copy: "Kopēt", copied: "Nokopēts!", upgrade: "Jaunināt", tryAgain: "Mēģināt vēlreiz", signOut: "Iziet", settings: "Iestatījumi", done: "Gatavs" },
    home: { title: "Panelis", newQuote: "Jauns Piedāvājums", recent: "Jaunākie", chaseUp: "Atgādinājumi", newRequests: "Jauni Pieprasījumi", revenueThisMonth: "Ieņēmumi šomēnes", acceptanceRate: "Pieņemšanas rādītājs", outstandingQuotes: "Gaidošie piedāvājumi", depositsWaiting: "Gaidošie avansi", noQuotes: "Vēl nekas — pieskarieties Jauns Piedāvājums.", sentAgo: "{n}d. atpakaļ · bez atbildes", noReply: "bez atbildes", chaseViaWhatsapp: "Atgādināt WhatsApp", getStarted: "Sāciet 3 soļos", step1: "Pievienot uzņēmuma nosaukumu", step1sub: "Iestatījumi → Uzņēmums", step2: "Ierakstīt pirmo darbu", step2sub: "Pieskarieties Jauns Piedāvājums", step3: "Nosūtīt klientam", step3sub: "Caur WhatsApp vai e-pastu sekundēs", limitReached: "Mēneša limits sasniegts — jauniniet plānu", lastQuote: "Pēdējais bezmaksas piedāvājums", quoteThemButton: "Piedāvāt" },
    quote: { newTitle: "Jauns Piedāvājums", reviewTitle: "Pārskatīt", sendTitle: "Sūtīt", customer: "Klients", address: "Adrese", email: "E-pasts", notes: "Piezīmes", materials: "Materiāli", labour: "Darbs", total: "Kopā", deposit: "Avansa maksājums", validFor: "Derīgs", days: "d.", addItem: "Pievienot pozīciju", deleteItem: "Dzēst", priceUpdated: "Cena atjaunināta", generate: "Ģenerēt Piedāvājumu", generating: "Ģenerē…", recording: "Ieraksta…", stopRecording: "Apstāties", startRecording: "Turiet, lai ierakstītu", orTypeBelow: "Vai rakstiet zemāk", describeJob: "Aprakstiet darbu…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "E-pasts", copyLink: "Kopēt saiti", downloadPdf: "PDF", duplicate: "Dublēt", markDeclined: "Atzīmēt kā noraidītu", invoice: "Rēķins", expiresOn: "Beidzas", expired: "Beidzies", subtotal: "Starpsumma (bez PVN)", vatAmount: "PVN (20%)", totalIncVat: "Kopā ar PVN", noBankDetails: "Nav bankas datu", noBankDetailsSub: "Pievienojiet Iestatījumos." },
    analytics: { title: "Statistika", totalQuoted: "Kopā piedāvāts", accepted: "Pieņemts", totalRevenue: "Kopējie ieņēmumi", averageQuote: "Vidējais piedāvājums", depositsWaiting: "Gaidošie avansi", byStatus: "Pēc statusa", taxEstimate: "HMRC nodokļu aprēķins", taxSub: "Pamatojoties uz pieņemtajiem ieņēmumiem", expenses: "Uzņēmuma izdevumi (£)", grossRevenue: "Bruto ieņēmumi", lessExpenses: "Atņemot izdevumus", taxableProfit: "Apliekamā peļņa", incomeTax: "Ienākuma nodoklis (apr.)", classNI: "NI 4. klase (apr.)", totalTax: "Kopā nodokļi", effectiveRate: "Efektīvā nodokļa likme", paymentsOnAccount: "Avansa maksājumi", setAside: "Atlikt", perMonth: "mēnesī", disclaimer: "Tikai aprēķins. Konsultējieties ar grāmatvedi." },
    history: { title: "Visi Piedāvājumi", search: "Meklēt piedāvājumus…", noResults: "Rezultātu nav." },
    settings: { title: "Iestatījumi", business: "Uzņēmums", bankDetails: "Bankas Dati", quoteDefaults: "Noklusējuma Iestatījumi", notifications: "Paziņojumi", appearance: "Izskats", language: "Valoda", billing: "Norēķini", account: "Konts", businessName: "Uzņēmuma nosaukums", trade: "Specialitāte", phone: "Tālrunis", bankName: "Bankas nosaukums", sortCode: "Bankas kods", accountNumber: "Konta numurs", paymentLink: "Maksājuma saite", googleReviewLink: "Google atsauksmju saite", validDays: "Derīguma dienas", depositDefault: "Avansa noklusējums", depositPercent: "Avansa %", vatRegistered: "PVN maksātājs", vatNumber: "PVN numurs", quotePrefix: "Piedāvājuma prefikss", startingNumber: "Sākuma numurs", paymentTerms: "Maksājuma nosacījumi", exclusions: "Standarta izslēgumi", notifyAccepted: "Paziņot pie pieņemšanas", theme: "Dizains", light: "Gaišs", dark: "Tumšs", system: "Sistēmas", saveChanges: "Saglabāt Izmaiņas", completeSetup: "Aizpildiet profilu", completeSetupSub: "Pievienojiet uzņēmuma nosaukumu un bankas datus.", currentPlan: "Pašreizējais plāns", manageBilling: "Pārvaldīt norēķinus", upgradePlan: "Jaunināt plānu", quoteNumbering: "Numerācija", quoteTemplate: "Piedāvājuma veidne", priceBook: "Cenrādis", shareLink: "Pieprasījuma saite", data: "Dati", about: "Par", emailAddress: "E-pasta adrese", newPassword: "Jauna parole", updatePassword: "Atjaunināt paroli", branding: "Zīmols" },
    portal: { from: "Piedāvājums no", jobTitle: "Darbs", quoteRef: "Piedāvājuma nr.", validUntil: "Derīgs līdz", expired: "Šis piedāvājums ir beidzies", acceptQuote: "Pieņemt Piedāvājumu", declineQuote: "Noraidīt", askQuestion: "Uzdot jautājumu", accepted: "Piedāvājums Pieņemts", acceptedSub: "Paldies! Sazināsimies.", declined: "Piedāvājums Noraidīts", declinedSub: "Paldies par atbildi.", signHere: "Parakstiet šeit", clearSignature: "Notīrīt", confirmAccept: "Apstiprināt un Pieņemt", depositDue: "Maksājams avans", finalPaymentDue: "Galīgais maksājums", payDeposit: "Maksāt avansu", payFinal: "Maksāt atlikumu" },
  },

  uk: {
    nav: { home: "ГОЛОВНА", quotes: "КОШТОРИСИ", stats: "СТАТИСТИКА" },
    status: { draft: "Чернетка", sent: "Надіслано", accepted: "Прийнято", declined: "Відхилено" },
    common: { save: "Зберегти", saving: "Збереження…", saved: "Збережено", cancel: "Скасувати", edit: "Редагувати", delete: "Видалити", send: "Надіслати", view: "Переглянути", back: "Назад", loading: "Завантаження…", confirm: "Підтвердити", close: "Закрити", add: "Додати", remove: "Видалити", copy: "Копіювати", copied: "Скопійовано!", upgrade: "Оновити", tryAgain: "Спробувати знову", signOut: "Вийти", settings: "Налаштування", done: "Готово" },
    home: { title: "Панель", newQuote: "Новий Кошторис", recent: "Останні", chaseUp: "Нагадування", newRequests: "Нові Запити", revenueThisMonth: "Дохід цього місяця", acceptanceRate: "Рівень прийняття", outstandingQuotes: "Очікуючі кошториси", depositsWaiting: "Очікуючі аванси", noQuotes: "Ще нічого — натисніть Новий Кошторис.", sentAgo: "{n}д тому · без відповіді", noReply: "без відповіді", chaseViaWhatsapp: "Нагадати через WhatsApp", getStarted: "Почніть за 3 кроки", step1: "Додайте назву компанії", step1sub: "Налаштування → Компанія", step2: "Запишіть перше замовлення", step2sub: "Натисніть Новий Кошторис", step3: "Надішліть клієнту", step3sub: "Через WhatsApp або email за секунди", limitReached: "Місячний ліміт досягнуто — оновіть план", lastQuote: "Останній безкоштовний кошторис місяця", quoteThemButton: "Кошторис" },
    quote: { newTitle: "Новий Кошторис", reviewTitle: "Перегляд Кошторису", sendTitle: "Надіслати Кошторис", customer: "Клієнт", address: "Адреса", email: "Email", notes: "Нотатки", materials: "Матеріали", labour: "Робота", total: "Разом", deposit: "Аванс", validFor: "Дійсний", days: "дн.", addItem: "Додати позицію", deleteItem: "Видалити", priceUpdated: "Ціна оновлена", generate: "Згенерувати Кошторис", generating: "Генерація…", recording: "Запис…", stopRecording: "Стоп", startRecording: "Тримайте для запису", orTypeBelow: "Або введіть нижче", describeJob: "Опишіть роботу…", sendViaWhatsapp: "WhatsApp", sendViaEmail: "Email", copyLink: "Копіювати посилання", downloadPdf: "PDF", duplicate: "Дублювати", markDeclined: "Позначити як відхилений", invoice: "Рахунок", expiresOn: "Дійсний до", expired: "Прострочено", subtotal: "Проміжна сума (без ПДВ)", vatAmount: "ПДВ (20%)", totalIncVat: "Разом з ПДВ", noBankDetails: "Немає банківських даних", noBankDetailsSub: "Додайте в Налаштуваннях." },
    analytics: { title: "Статистика", totalQuoted: "Всього кошторисів", accepted: "Прийнято", totalRevenue: "Загальний дохід", averageQuote: "Середній кошторис", depositsWaiting: "Очікуючі аванси", byStatus: "За статусом", taxEstimate: "Оцінка податку HMRC", taxSub: "На основі прийнятих доходів", expenses: "Витрати підприємства (£)", grossRevenue: "Валовий дохід", lessExpenses: "Мінус витрати", taxableProfit: "Оподатковуваний прибуток", incomeTax: "Прибутковий податок (оцін.)", classNI: "NI Клас 4 (оцін.)", totalTax: "Загальний податок", effectiveRate: "Ефективна ставка оподаткування", paymentsOnAccount: "Авансові платежі", setAside: "Відкласти", perMonth: "на місяць", disclaimer: "Лише оцінка. Проконсультуйтесь з бухгалтером." },
    history: { title: "Всі Кошториси", search: "Пошук кошторисів…", noResults: "Результатів не знайдено." },
    settings: { title: "Налаштування", business: "Компанія", bankDetails: "Банківські Дані", quoteDefaults: "Налаштування за Замовчуванням", notifications: "Сповіщення", appearance: "Зовнішній вигляд", language: "Мова", billing: "Розрахунки", account: "Акаунт", businessName: "Назва компанії", trade: "Спеціальність", phone: "Телефон", bankName: "Назва банку", sortCode: "Код банку", accountNumber: "Номер рахунку", paymentLink: "Посилання для оплати", googleReviewLink: "Посилання відгуків Google", validDays: "Дні дійсності", depositDefault: "Аванс за замовчуванням", depositPercent: "% авансу", vatRegistered: "Платник ПДВ", vatNumber: "Номер ПДВ", quotePrefix: "Префікс кошторису", startingNumber: "Початковий номер", paymentTerms: "Умови оплати", exclusions: "Стандартні виключення", notifyAccepted: "Сповіщати при прийнятті", theme: "Тема", light: "Світла", dark: "Темна", system: "Системна", saveChanges: "Зберегти Зміни", completeSetup: "Заповніть профіль", completeSetupSub: "Додайте назву компанії та банківські дані.", currentPlan: "Поточний план", manageBilling: "Керувати розрахунками", upgradePlan: "Оновити план", quoteNumbering: "Нумерація кошторисів", quoteTemplate: "Шаблон кошторису", priceBook: "Прайс-лист", shareLink: "Посилання для запиту", data: "Дані", about: "Про застосунок", emailAddress: "Адреса електронної пошти", newPassword: "Новий пароль", updatePassword: "Оновити пароль", branding: "Брендинг" },
    portal: { from: "Кошторис від", jobTitle: "Робота", quoteRef: "№ кошторису", validUntil: "Дійсний до", expired: "Термін дії цього кошторису закінчився", acceptQuote: "Прийняти Кошторис", declineQuote: "Відхилити", askQuestion: "Поставити запитання", accepted: "Кошторис Прийнято", acceptedSub: "Дякуємо! Ми зв'яжемося з вами.", declined: "Кошторис Відхилено", declinedSub: "Дякуємо за відповідь.", signHere: "Підпишіть тут", clearSignature: "Очистити", confirmAccept: "Підтвердити та Прийняти", depositDue: "Аванс до сплати", finalPaymentDue: "Кінцевий платіж", payDeposit: "Сплатити аванс", payFinal: "Сплатити залишок" },
  },
};

